---
- name: Ensure git is installed
  become: true
  apt:
    pkg: "git"
    state: present

- name: Cloning Powerline fonts
  become: no
  git:
    repo: "{{ powerline_fonts_repo }}"
    dest: "{{ powerline_fonts_dir }}"
    accept_hostkey: no

- name: Installing Powerline fonts
  become: no
  shell: "{{ powerline_fonts_dir }}/install.sh"

