---
- name: Installing Pip
  become: true
  apt:
    pkg: "python-pip"
    state: latest
  when: ansible_os_family == "Debian"

- name: Installing Powerline
  become: true
  pip:
    name: "{{ powerline_package_name }}"
    version: "{{ powerline_version }}"
    state: present
  when: powerline_version != ""

- name: Installing Powerline
  become: true
  pip:
    name: "{{ powerline_package_name }}"
    state: present
  when: powerline_version == ""

- name: Installing Powerline extra segments
  become: true
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ powerline_extra_segments }}"
