---
- name: Installing Pip
  become: true
  apt:
    pkg: "python-pip"
    state: latest

- name: Installing Powerline pip packages
  become: true
  pip:
    name: "{{ item }}"
  with_items: "{{ powerline_pip_packages }}"

- name: Cloning Powerline fonts
  become_user: "{{ user }}"
  git:
    repo: "{{ powerline_fonts_repo }}"
    dest: "{{ powerline_config_dir }}/fonts"
    accept_hostkey: yes

- name: Installing Powerline fonts
  shell: "{{ powerline_config_dir }}/fonts/install.sh"
